### ISSUE TITLE
migration fild

### ISSUE THREAD

**Issue by Grinivs** [pktharindu/nova-permissions#2]
I get this issue 
![image](https://user-images.githubusercontent.com/40636030/57457795-7b2d9800-7270-11e9-951f-57ac9984d6a8.png)

**Comment by naingyeyint** [comment]
+1

**Comment by gvsrepins** [comment]
I also get stuck on this issue. But I figured out how to solve it.

The problem is the type of the `user_id` field on the `role_user` table. It is defined by default on the migrations plugin as  `unsignedBigInteger` as this is the new Laravel pattern.

To fix the issue, you need to either change it to   `$table->unsignedInteger('user_id');` to return it to the old pattern, or update the `users`  table and make conform with the new pattern, like so `$table->bigIncrements('id');` 

Hope it helps!
